routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\TipoAnimal;

Route::get('/', 'ControleController@index');

Route::resource('controle','ControleController');
Route::resource('tipoanimal','TipoAnimalController');
Route::resource('tipofrete','TipoFreteController');
Route::resource('faixafrete','FaixaFreteController');
Route::get('relatorio/geral','RelatorioController@geral')->name('relatorio.geral');
Route::get('relatorio/dia','RelatorioController@dia')->name('relatorio.dia');
Route::get('relatorio/imprimir','RelatorioController@imprimir')->name('relatorio.imprimir');

app/TipoFrete.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TipoFrete extends Model
{
    protected $table = 'tipo_frete';
}

app/Http/Controllers/TipoFreteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\TipoFrete;

class TipoFreteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $tipos = TipoFrete::all();
        return view('tipofrete.index', ['tipos' => $tipos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->index();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $descricao = $request->input('descricao');
        $quantidade = intval($request->input('quantidade'));

        $tipo = new TipoFrete();
        $tipo->descricao = $descricao;
        $tipo->quantidade_animais = $quantidade;
        $tipo->save();

        $tipos = TipoFrete::all();
        return view('tipofrete.index', ['tipos' => $tipos])->with('msg', 'Cadastrado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\TipoFrete $tipoFrete
     * @return \Illuminate\Http\Response
     */
    public function show(TipoFrete $tipoFrete)
    {
        return $this->index();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\TipoFrete $tipoFrete
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tipoFrete = TipoFrete::find($id);
        $tipos = TipoFrete::all();
        return view('tipofrete.index', ['tipos' => $tipos, 'tipo' => $tipoFrete]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->input('descricao') != '')
            $descricao = $request->input('descricao');
        if ($request->input('quantidade') != '')
            $quantidade = intval($request->input('quantidade'));

        $tipo = TipoFrete::find($id);
        if ($request->input('descricao') != '')
            $tipo->descricao = $descricao;
        if ($request->input('quantidade') != '')
            $tipo->quantidade_animais = $quantidade;
        $tipo->save();

        return $this->index()->with('msg', 'Atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tipoFrete = TipoFrete::find($id);
        $tipoFrete->delete();

        return $this->index()->with('msg', 'Removido com sucesso!');
    }
}

resources/views/tipofrete/index.blade.php
@extends('template')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h2>
                        Tipos de Frete <a class="btn btn-outline-primary btn-sm"
                                            href="{{route('tipofrete.create')}}">Adicionar Novo</a>
                    </h2>
                    <hr>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <form method="post"
                      action="{{isset($tipo)?route('tipofrete.update', ['id' => $tipo->id]):route('tipofrete.store')}}">
                    @if(isset($tipo)) <input type="hidden" name="_method" value="PUT"> @endif
                        {{ csrf_field() }}

                    <div class="form-group">
                        <label for="descricao">Descrição</label>
                        <input value="{{isset($tipo)?$tipo->descricao:''}}" id="descricao" name="descricao" type="text"
                               class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="quantidade">Quantidade de Animais</label>
                        <input value="{{isset($tipo)?$tipo->quantidade_animais:''}}" id="quantidade" name="quantidade" type="text"
                               class="form-control">
                    </div>
                    <button type="submit" class="btn btn-success">{{isset($tipo)?'Atualizar':'Cadastrar'}}</button>
                </form>
            </div>
            <div class="col-md-8">
                <table class="table table-striped">
                    <thead>
                    <th>#</th>
                    <th>Descricao</th>
                    <th>Quantidade de Animais</th>
                    <th>Ações</th>
                    </thead>
                    <tbody>
                    @forelse($tipos as $tipo)
                        <tr>
                            <td>{{$tipo->id}}</td>
                            <td>{{$tipo->descricao}}</td>
                            <td>{{$tipo->quantidade_animais}}</td>
                            <td><a href="{{route('tipofrete.edit', $tipo)}}"
                                   class="btn btn-sm btn-primary">Editar</a>
                                <form style="display: inline-block;" method="POST" action="{{route('tipofrete.destroy', $tipo->id)}}">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <button
                                            class="btn btn-sm btn-danger">Excluir</button></form></td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="4"><strong>Nenhum item encontrado!</strong></td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection