routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\TipoAnimal;

Route::get('/', 'ControleController@index');

Route::resource('controle','ControleController');
Route::resource('tipoanimal','TipoAnimalController');
Route::resource('tipofrete','TipoFreteController');
Route::resource('faixafrete','FaixaFreteController');
Route::get('relatorio/geral','RelatorioController@geral')->name('relatorio.geral');
Route::get('relatorio/dia','RelatorioController@dia')->name('relatorio.dia');
Route::get('relatorio/imprimir','RelatorioController@imprimir')->name('relatorio.imprimir');

app/TipoAnimal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TipoAnimal extends Model
{
    protected $table = 'tipo_animal';
}

app/Http/Controllers/TipoAnimalController.php
<?php

namespace App\Http\Controllers;

use App\TipoAnimal;
use Illuminate\Http\Request;

class TipoAnimalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tipos = TipoAnimal::all();
        return view('tipoanimal.index', ['tipos' => $tipos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tipos = TipoAnimal::all();
        return view('tipoanimal.index', ['tipos' => $tipos]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $descricao = $request->input('descricao');
        $faixa_1 = floatval($request->input('peso_inicial'));
        $faixa_2 = floatval($request->input('peso_final'));
        $desconto = floatval($request->input('desconto'));

        $tipo = new TipoAnimal();
        $tipo->descricao = $descricao;
        $tipo->faixa_1 = $faixa_1;
        $tipo->faixa_2 = $faixa_2;
        $tipo->desconto = $desconto;
        $tipo->save();

        return $this->index()->with('msg', 'Cadastrado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\TipoAnimal $tipoAnimal
     * @return \Illuminate\Http\Response
     */
    public function show(TipoAnimal $tipoAnimal)
    {
        $tipos = TipoAnimal::all();
        return view('tipoanimal.index', ['tipos' => $tipos, 'tipo' => $tipoAnimal]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\TipoAnimal $tipoAnimal
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tipoAnimal = TipoAnimal::find($id);
        return $this->index()->with('tipo', $tipoAnimal);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\TipoAnimal $tipoAnimal
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->input('descricao') != '')
            $descricao = $request->input('descricao');
        if ($request->input('peso_inicial') != '')
            $faixa_1 = floatval($request->input('peso_inicial'));
        if ($request->input('peso_final') != '')
            $faixa_2 = floatval($request->input('peso_final'));
        if ($request->input('desconto') != '')
            $desconto = floatval($request->input('desconto'));

        $tipo = TipoAnimal::find($id);
        if ($request->input('descricao') != '')
            $tipo->descricao = $descricao;
        if ($request->input('peso_inicial') != '')
            $tipo->faixa_1 = $faixa_1;
        if ($request->input('peso_final') != '')
            $tipo->faixa_2 = $faixa_2;
        if ($request->input('desconto') != '')
            $tipo->desconto = $desconto;
        $tipo->save();

        $tipos = TipoAnimal::all();
        return view('tipoanimal.index', ['tipos' => $tipos])->with('msg', 'Atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\TipoAnimal $tipoAnimal
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tipoAnimal = TipoAnimal::find($id);
        $tipoAnimal->delete();
        $tipos = TipoAnimal::all();
        return view('tipoanimal.index', ['tipos' => $tipos])->with('msg', 'Removido com sucesso!');
    }
}

resources/views/tipoanimal/index.blade.php
@extends('template')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h2>
                        Tipos de animais <a class="btn btn-outline-primary btn-sm"
                                            href="{{route('tipoanimal.create')}}">Adicionar Novo</a>
                    </h2>
                    <hr>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <form method="post"
                      action="{{isset($tipo)?route('tipoanimal.update', ['id' => $tipo->id]):route('tipoanimal.store')}}">
                    @if(isset($tipo)) <input type="hidden" name="_method" value="PUT"> @endif
                        {{ csrf_field() }}

                    <div class="form-group">
                        <label for="descricao">Descrição</label>
                        <input value="{{isset($tipo)?$tipo->descricao:''}}" id="descricao" name="descricao" type="text"
                               class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="peso_inicial">Peso Inicial</label>
                        <input value="{{isset($tipo)?$tipo->faixa_1:''}}" step="any" id="peso_inicial" name="peso_inicial"
                               type="number" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="peso_final">Peso Final</label>
                        <input value="{{isset($tipo)?$tipo->faixa_2:''}}" step="any" id="peso_final" name="peso_final"
                               type="number" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="desconto">Desconto (%)</label>
                        <input value="{{isset($tipo)?$tipo->desconto:''}}" step="any" id="desconto" name="desconto" type="number"
                               class="form-control">
                    </div>
                    <button type="submit" class="btn btn-success">{{isset($tipo)?'Atualizar':'Cadastrar'}}</button>
                </form>
            </div>
            <div class="col-md-8">
                <table class="table table-striped">
                    <thead>
                    <th>Descricao</th>
                    <th>Peso Inicial</th>
                    <th>Peso Final</th>
                    <th>Desconto</th>
                    <th>Ações</th>
                    </thead>
                    <tbody>
                    @forelse($tipos as $tipo)
                        <tr>
                            <td>{{$tipo->descricao}}</td>
                            <td>{{$tipo->faixa_1}}</td>
                            @if($tipo->faixa_2 == 0)
                                <td class="text-center"> -</td>
                            @else
                                <td>{{$tipo->faixa_2}}</td>
                            @endif
                            @if($tipo->desconto == 0)
                                <td class="text-center"> -</td>
                            @else
                                <td>{{$tipo->desconto}}%</td>
                            @endif
                            <td><a href="{{route('tipoanimal.edit', $tipo)}}"
                                   class="btn btn-sm btn-primary">Editar</a>
                                <form style="display: inline-block;" method="POST" action="{{route('tipoanimal.destroy', $tipo->id)}}">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <button
                                   class="btn btn-sm btn-danger">Excluir</button></form></td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5"><strong>Nenhum item encontrado!</strong></td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection