routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\TipoAnimal;

Route::get('/', 'ControleController@index');

Route::resource('controle','ControleController');
Route::resource('tipoanimal','TipoAnimalController');
Route::resource('tipofrete','TipoFreteController');
Route::resource('faixafrete','FaixaFreteController');
Route::get('relatorio/geral','RelatorioController@geral')->name('relatorio.geral');
Route::get('relatorio/dia','RelatorioController@dia')->name('relatorio.dia');
Route::get('relatorio/imprimir','RelatorioController@imprimir')->name('relatorio.imprimir');

app/FaixaFrete.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FaixaFrete extends Model
{
    protected $table = 'fretes';
}

app/Http/Controllers/FaixaFreteController.php
<?php

namespace App\Http\Controllers;

use App\FaixaFrete;
use App\TipoFrete;
use Illuminate\Http\Request;

class FaixaFreteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tipos = TipoFrete::all();
        $fretes = FaixaFrete::all();
        return view('faixafrete.index', ['fretes' => $fretes, 'tipos' => $tipos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->index();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $tipo = intval($request->input('tipo'));
        $descricao = $request->input('descricao');
        $faixa_1 = floatval($request->input('faixa_1'));
        $faixa_2 = floatval($request->input('faixa_2'));
        $valor = floatval($request->input('valor'));

        $frete = new FaixaFrete();
        $frete->tipo = $tipo;
        $frete->descricao = $descricao;
        $frete->faixa_1 = $faixa_1;
        $frete->faixa_2 = $faixa_2;
        $frete->valor = $valor;
        $frete->save();

        $tipos = TipoFrete::all();
        $fretes = FaixaFrete::all();
        return view('faixafrete.index', ['fretes' => $fretes, 'tipos' => $tipos])->with('msg', 'Cadastrado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\TipoFrete $faixaFrete
     * @return \Illuminate\Http\Response
     */
    public function show(TipoFrete $faixaFrete)
    {
        $fretes = TipoFrete::all();
        return view('faixafrete.index', ['tipos' => $fretes, 'tipo' => $faixaFrete]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\TipoFrete $faixaFrete
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $faixaFrete = FaixaFrete::find($id);
        $tipos = TipoFrete::all();
        $fretes = FaixaFrete::all();
        return view('faixafrete.index', ['tipos' => $tipos, 'frete' => $faixaFrete, 'fretes' => $fretes]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->input('tipo') != '')
            $tipo = $request->input('tipo');
        if ($request->input('descricao') != '')
            $descricao = $request->input('descricao');
        if ($request->input('faixa_1') != '')
            $faixa_1 = floatval($request->input('faixa_1'));
        if ($request->input('faixa_2') != '')
            $faixa_2 = floatval($request->input('faixa_2'));
        if ($request->input('valor') != '')
            $valor = floatval($request->input('valor'));


        $frete = FaixaFrete::find($id);
        if ($frete) {
            if ($request->input('tipo') != '')
                $frete->tipo = $tipo;
            if ($request->input('descricao') != '')
                $frete->descricao = $descricao;
            if ($request->input('faixa_1') != '')
                $frete->faixa_1 = $faixa_1;
            if ($request->input('faixa_2') != '')
                $frete->faixa_2 = $faixa_2;
            if ($request->input('valor') != '')
                $frete->valor = $valor;
            $frete->save();
        } else {
            return $this->index()->with('error', 'Faixa de frete não encontrada!');
        }

        return $this->index()->with('msg', 'Atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return \Illuminate\Http\Response
     */
    public
    function destroy($id)
    {
        $frete = FaixaFrete::find($id);
        if ($frete) {
            $frete->delete();
        }else{
            return $this->index()->with('error', 'Faixa de frete não encontrada!');
        }
        return $this->index()->with('msg', 'Removido com sucesso!');
    }
}

resources/views/faixafrete/index.blade.php
@extends('template')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h2>
                        Faixas de Frete <a class="btn btn-outline-primary btn-sm"
                                           href="{{route('faixafrete.create')}}">Adicionar Nova</a>
                    </h2>
                    <hr>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <form method="post"
                      action="{{isset($frete)?route('faixafrete.update', ['id' => $frete->id]):route('faixafrete.store')}}">
                    @if(isset($frete)) <input type="hidden" name="_method" value="PUT"> @endif
                        {{ csrf_field() }}

                    <div class="form-group">
                        <label for="tipo"><span class="required">*</span> Tipo de Frete</label>
                        <select required id="tipo" name="tipo" class="form-control">
                            <option value="">Selecione um Tipo</option>
                            @foreach($tipos as $tipo)
                                <option {{isset($frete) && $tipo->id = $frete->tipo?' selected ':''}} value="{{$tipo->id}}">{{$tipo->descricao}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="descricao">Descrição</label>
                        <input value="{{isset($frete)?$frete->descricao:''}}" id="descricao" name="descricao"
                               type="text"
                               class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="peso_inicial"><span class="required">*</span> Distância Inicial (km)</label>
                        <input required value="{{isset($frete)?$frete->faixa_1:''}}" step="any" id="faixa_1" name="faixa_1"
                               type="number" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="peso_final">Distância Final (km)</label>
                        <input value="{{isset($frete)?$frete->faixa_2:''}}" step="any" id="faixa_2" name="faixa_2"
                               type="number" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="valor"><span class="required">*</span> Valor</label>
                        <input required value="{{isset($frete)?$frete->valor:''}}" step="any" id="valor" name="valor"
                               type="number"
                               class="form-control">
                    </div>
                    <button type="submit" class="btn btn-success">{{isset($frete)?'Atualizar':'Cadastrar'}}</button>
                </form>
            </div>
            <div class="col-md-8">
                <table class="table table-striped">
                    <thead>
                    <th>Tipo</th>
                    <th>Descricao</th>
                    <th>Distância Inicial</th>
                    <th>Distância Final</th>
                    <th>Valor</th>
                    <th>Ações</th>
                    </thead>
                    <tbody>
                    @forelse($fretes as $frete)
                        <tr>
                            @foreach($tipos as $tipo)
                                @if($tipo->id == $frete->tipo)
                                    <td>{{$tipo->descricao}}</td>
                                @endif
                            @endforeach
                            <td>{{$frete->descricao}}</td>
                            <td>{{$frete->faixa_1}} km</td>
                            @if($frete->faixa_2 == 0)
                                <td class="text-center"> -</td>
                            @else
                                <td>{{$frete->faixa_2}} km</td>
                            @endif
                            @if($frete->valor == 0)
                                <td class="text-center"> -</td>
                            @else
                                <td>R$ {{$frete->valor}}</td>
                            @endif
                            <td><a href="{{route('faixafrete.edit', $frete)}}"
                                   class="btn btn-sm btn-primary">Editar</a>
                                <form style="display: inline-block;" method="POST"
                                      action="{{route('faixafrete.destroy', $frete->id)}}">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <button
                                            class="btn btn-sm btn-danger">Excluir
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5"><strong>Nenhum item encontrado!</strong></td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection